changed classspath to include ctrlib-sources
RoboticsTeam4904/2016-Code pull request #81
Opened 2017-02-14 01:20 UTC by ave4224

2017-02-14 01:22 UTC, tylkahn commented
👍

2017-02-14 01:23 UTC, tylkahn approved these changes
Meh

2017-02-14 01:34 UTC, c0d3rman approved these changes

2017-02-14 01:34 UTC, c0d3rman commented on .classpath
> +    <classpathentry kind="var" path="opencv" sourcepath="opencv.sources"/>
Remove this

2017-02-14 01:34 UTC, c0d3rman commented on .classpath
> +    <classpathentry kind="var" path="cscore" sourcepath="cscore.sources"/>
Remove this

2017-02-14 01:34 UTC, c0d3rman commented on .classpath
> +    <classpathentry kind="var" path="USERLIBS_DIR/navx_frc-sources.jar"/>
Remove this

2017-02-14 01:34 UTC, c0d3rman commented on .classpath
> +    <classpathentry kind="var" path="USERLIBS_DIR/CTRLib-javadoc.jar"/>
Does this work?

2017-02-16 02:09 UTC, c0d3rman requested changes
a

2017-02-17 01:00 UTC, c0d3rman approved these changes

2017-02-17 01:01 UTC, merged